[build-system]
requires = ["setuptools>=46.4.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cwordtm"
authors = [{name = "????", email = "????@gmail.com"}]
dynamic = ["version", "description"]
